### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by fmalina** [Alir3z4/django-databrowse#19]
Django databrowse is affected most importantly by:
- `_meta` changes:
  https://docs.djangoproject.com/en/1.9/ref/models/meta/#migrating-old-meta-api
- `get_models` and `get_model` are now in `from django.apps import apps`
- URL `patterns` are deprecated, just use a list of `url` functions

**Comment by Alir3z4** [comment]
@fmalina Pull request #21 has been merged into and claims to be fixing the issue for Django 1.9, could you try the latest from the master branch and let me know about it ?

If it fixes the issue, I'll be releasing a new version
