### ISSUE TITLE
Can you make a new release? (for django 1.10 support)

### ISSUE THREAD

**Issue by nikolas** [Alir3z4/django-databrowse#33]
Hi @Alir3z4 - it looks like django 1.10 support has been added to this library, but the most recent release was in 2016. Can you make a new release? Also, I'd be happy to help out. Thanks.

**Comment by Alir3z4** [comment]
Yes we can.
However, since we're going to release a new version could you please check https://github.com/Alir3z4/django-databrowse/pull/34 so we can include that one as well?

**Comment by nikolas** [comment]
We've forked this library and are maintaining it here for now: https://github.com/ccnmtl/django-databrowse

**Comment by Alir3z4** [comment]
If we could have https://github.com/Alir3z4/django-databrowse/pull/39 passing it would be great and we can make a good release that has support for python 3.7.

Also, to make things easier and I don't be a blocker, I can add you as a maintainer on the pypi repo as well so you can make release too.
